/**
 * Copyright (C) 2015 Smithsonian Astrophysical Observatory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cfa.vo.visualizer.fitting;

import cfa.vo.iris.IWorkspace;
import cfa.vo.iris.sed.ExtSed;
import cfa.vo.sherpa.models.AbstractModel;
import java.util.ArrayList;
import java.util.List;


public class FittingToolGUI extends javax.swing.JInternalFrame {
    
    IWorkspace ws;
    ExtSed sed;
    
    // Constants used to access Sherpa response map.
    private static final String RSTAT = "rstat";
    private static final String QVAL = "qval";
    private static final String DOF = "dof";
    private static final String NUMPOINTS = "numpoints";
    private static final String NFEV = "nfev";
    private static final String STATVAL = "statval";
    private static List<String> fittingParameterNames = new ArrayList<String>();
    private static List<String> fittingParameterDescriptions = new ArrayList<String>();

    static {
        fittingParameterNames.add(STATVAL);
        fittingParameterNames.add(RSTAT);
        fittingParameterNames.add(QVAL);
        fittingParameterNames.add(DOF);
        fittingParameterNames.add(NUMPOINTS);
        fittingParameterNames.add(NFEV);
        fittingParameterDescriptions.add("Final fit statistic: ");
        fittingParameterDescriptions.add("Reduced statistic: ");
        fittingParameterDescriptions.add("Probability [Q-value]: ");
        fittingParameterDescriptions.add("Degrees of freedom: ");
        fittingParameterDescriptions.add("Data points: ");
        fittingParameterDescriptions.add("Last function evaluation:");
    }

    /**
     * Creates new form FittingToolGUI
     * 
     * @param ws
     * @throws Exception
     */
    public FittingToolGUI(IWorkspace ws) throws Exception {
        this.ws = ws;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileMenu1 = new javax.swing.JMenu();
        loadModelMenuItem1 = new javax.swing.JMenuItem();
        saveModelMenuItem1 = new javax.swing.JMenuItem();
        writeToTextMenu1 = new javax.swing.JMenu();
        writeActiveComponentsMenuItem1 = new javax.swing.JMenuItem();
        writeAllComponentsMenuItem1 = new javax.swing.JMenuItem();
        preferencesMenuItem1 = new javax.swing.JMenuItem();
        editMenu1 = new javax.swing.JMenu();
        undoMenuItem1 = new javax.swing.JMenuItem();
        redoMenuItem1 = new javax.swing.JMenuItem();
        modelsMenu1 = new javax.swing.JMenu();
        presetModelsMenu1 = new javax.swing.JMenu();
        customModelsMenu1 = new javax.swing.JMenu();
        importModelMenuItem1 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        thawMenuItem1 = new javax.swing.JMenuItem();
        freezeMenuItem1 = new javax.swing.JMenuItem();
        helpMenu1 = new javax.swing.JMenu();
        helpContentsMenuItem1 = new javax.swing.JMenuItem();
        helpOnlineMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        modelExpressionLabel = new javax.swing.JLabel();
        modelExpressionTextField = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel6 = new javax.swing.JPanel();
        modelComponentsScrollPane = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        modelPropertiesPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        loadModelMenuItem = new javax.swing.JMenuItem();
        saveModelMenuItem = new javax.swing.JMenuItem();
        writeToTextMenu = new javax.swing.JMenu();
        writeActiveComponentsMenuItem = new javax.swing.JMenuItem();
        writeAllComponentsMenuItem = new javax.swing.JMenuItem();
        preferencesMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        modelsMenu = new javax.swing.JMenu();
        presetModelsMenu = new javax.swing.JMenu();
        customModelsMenu = new javax.swing.JMenu();
        importModelMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        thawMenuItem = new javax.swing.JMenuItem();
        freezeMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        helpContentsMenuItem = new javax.swing.JMenuItem();
        helpOnlineMenuItem = new javax.swing.JMenuItem();
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Fitting Tool: Sed0");
        fileMenu1.setText("File");
        loadModelMenuItem1.setText("Load model");
        fileMenu1.add(loadModelMenuItem1);
        saveModelMenuItem1.setText("Save model");
        fileMenu1.add(saveModelMenuItem1);
        writeToTextMenu1.setText("Write to text file");
        writeActiveComponentsMenuItem1
                .setText("Write active components to text file");
        writeToTextMenu1.add(writeActiveComponentsMenuItem1);
        writeAllComponentsMenuItem1
                .setText("Write all components to text file");
        writeToTextMenu1.add(writeAllComponentsMenuItem1);
        fileMenu1.add(writeToTextMenu1);
        preferencesMenuItem1.setText("Preferences");
        fileMenu1.add(preferencesMenuItem1);
        jMenuBar2.add(fileMenu1);
        editMenu1.setText("Edit");
        undoMenuItem1.setText("Undo");
        editMenu1.add(undoMenuItem1);
        redoMenuItem1.setText("Redo");
        editMenu1.add(redoMenuItem1);
        jMenuBar2.add(editMenu1);
        modelsMenu1.setText("Models");
        presetModelsMenu1.setText("Preset models");
        modelsMenu1.add(presetModelsMenu1);
        customModelsMenu1.setText("Custom models");
        modelsMenu1.add(customModelsMenu1);
        importModelMenuItem1.setText("Import model");
        modelsMenu1.add(importModelMenuItem1);
        modelsMenu1.add(jSeparator2);
        thawMenuItem1.setText("Thaw all parameters");
        modelsMenu1.add(thawMenuItem1);
        freezeMenuItem1.setText("Freeze all parameters");
        modelsMenu1.add(freezeMenuItem1);
        jMenuBar2.add(modelsMenu1);
        helpMenu1.setText("Help");
        helpContentsMenuItem1.setText("Help Contents");
        helpMenu1.add(helpContentsMenuItem1);
        helpOnlineMenuItem1.setText("Online user docs");
        helpMenu1.add(helpOnlineMenuItem1);
        jMenuBar2.add(helpMenu1);
        jInternalFrame1.setJMenuBar(jMenuBar2);
        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(
                jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(jInternalFrame1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));
        jInternalFrame1Layout.setVerticalGroup(jInternalFrame1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));
        jPanel1.setBorder(
                javax.swing.BorderFactory.createTitledBorder("Build Model"));
        modelExpressionLabel.setText("Model Expression:");
        jSplitPane1.setDividerLocation(190);
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6,
                javax.swing.BoxLayout.Y_AXIS));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode(
                "Model Components");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(
                "powerlaw.c1");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(
                "c1.ampl");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c1.index");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c1.refer");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("blackbody.c2");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c2.ampl");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c2.refer");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c2.temp");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(
                "mytemplatelib.c3");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c3.ampl");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c3.index");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c3.temp");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("c3.refer");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        modelComponentsScrollPane.setViewportView(jTree1);
        jPanel6.add(modelComponentsScrollPane);
        jPanel7.setFocusable(false);
        jPanel7.setMaximumSize(new java.awt.Dimension(32767, 30));
        jPanel7.setPreferredSize(new java.awt.Dimension(192, 30));
        jButton6.setText("Add");
        jButton8.setText("Remove");
        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
                jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(jPanel7Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap().addComponent(jButton6)
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)));
        jPanel7Layout.setVerticalGroup(jPanel7Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton6).addComponent(jButton8))
                        .addGap(0, 0, Short.MAX_VALUE)));
        jPanel6.add(jPanel7);
        jSplitPane1.setLeftComponent(jPanel6);
        javax.swing.GroupLayout modelPropertiesPanelLayout = new javax.swing.GroupLayout(
                modelPropertiesPanel);
        modelPropertiesPanel.setLayout(modelPropertiesPanelLayout);
        modelPropertiesPanelLayout.setHorizontalGroup(modelPropertiesPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 633, Short.MAX_VALUE));
        modelPropertiesPanelLayout.setVerticalGroup(modelPropertiesPanelLayout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 261, Short.MAX_VALUE));
        jSplitPane1.setRightComponent(modelPropertiesPanel);
        jLabel6.setText("Range:");
        jButton7.setText("Set fitting range");
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
                jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSplitPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(modelExpressionLabel)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(modelExpressionTextField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                358,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton7)))
                        .addContainerGap()));
        jPanel1Layout.setVerticalGroup(jPanel1Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        jPanel1Layout.createSequentialGroup().addContainerGap()
                                .addGroup(jPanel1Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(modelExpressionLabel)
                                        .addComponent(modelExpressionTextField,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jButton7))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSplitPane1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        265,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));
        jPanel2.setBorder(
                javax.swing.BorderFactory.createTitledBorder("Fit Model"));
        jPanel3.setBorder(javax.swing.BorderFactory
                .createTitledBorder("Fitting Options"));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "neldermead", "levenmar", "montecar" }));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(
                new String[] { "leastsq", "chi2datavar" }));
        jLabel1.setText("Optimization:");
        jLabel2.setText("Statistic:");
        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
                jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));
        jPanel5Layout.setVerticalGroup(jPanel5Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE));
        jButton3.setText("Stop");
        jButton2.setText("Fit");
        jButton1.setText("Evaluate");
        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
                jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel3Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel5,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                .addGroup(jPanel3Layout
                                                        .createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(
                                                                jComboBox1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26)
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(
                                                                jComboBox2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0,
                                                                Short.MAX_VALUE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap()));
        jPanel3Layout.setVerticalGroup(jPanel3Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                        jPanel3Layout.createSequentialGroup().addContainerGap()
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jComboBox1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jComboBox2,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1))));
        jPanel4.setBorder(
                javax.swing.BorderFactory.createTitledBorder("Confidence"));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] { { null, null, null }, { null, null, null },
                        { null, null, null }, { null, null, null } },
                new String[] { "Parameter", "Upper", "Lower" }) {
            boolean[] canEdit = new boolean[] { false, false, false };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jLabel3.setText("Input sigma:");
        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setText("Sigma:");
        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel5.setText("Percent:");
        jButton4.setText("Start");
        jButton5.setText("Stop");
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
                jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel4Layout
                                                        .createSequentialGroup()
                                                        .addComponent(jLabel4)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)
                                                        .addComponent(jButton4)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jButton5))
                                                .addGroup(jPanel4Layout
                                                        .createSequentialGroup()
                                                        .addGroup(jPanel4Layout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(
                                                                        jPanel4Layout
                                                                                .createSequentialGroup()
                                                                                .addComponent(
                                                                                        jLabel3)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(
                                                                                        jTextField1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        119,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(
                                                                        jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        355,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0,
                                                                Short.MAX_VALUE)))
                                        .addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel5).addContainerGap(
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)))));
        jPanel4Layout.setVerticalGroup(jPanel4Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3).addComponent(jTextField1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1,
                                javax.swing.GroupLayout.PREFERRED_SIZE, 132,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(
                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)
                                        .addGap(0, 29, Short.MAX_VALUE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel4Layout
                                                .createParallelGroup(
                                                        javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jButton4)
                                                .addComponent(jButton5))))
                        .addContainerGap()));
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
                jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)));
        jPanel2Layout.setVerticalGroup(jPanel2Layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                        jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout
                                        .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel4,
                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE)
                                        .addComponent(jPanel3,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        fileMenu.setText("File");
        loadModelMenuItem.setText("Load model");
        fileMenu.add(loadModelMenuItem);
        saveModelMenuItem.setText("Save model");
        fileMenu.add(saveModelMenuItem);
        writeToTextMenu.setText("Write to text file");
        writeActiveComponentsMenuItem
                .setText("Write active components to text file");
        writeToTextMenu.add(writeActiveComponentsMenuItem);
        writeAllComponentsMenuItem.setText("Write all components to text file");
        writeToTextMenu.add(writeAllComponentsMenuItem);
        fileMenu.add(writeToTextMenu);
        preferencesMenuItem.setText("Preferences");
        fileMenu.add(preferencesMenuItem);
        jMenuBar1.add(fileMenu);
        editMenu.setText("Edit");
        undoMenuItem.setText("Undo");
        editMenu.add(undoMenuItem);
        redoMenuItem.setText("Redo");
        editMenu.add(redoMenuItem);
        jMenuBar1.add(editMenu);
        modelsMenu.setText("Models");
        presetModelsMenu.setText("Preset models");
        modelsMenu.add(presetModelsMenu);
        customModelsMenu.setText("Custom models");
        modelsMenu.add(customModelsMenu);
        importModelMenuItem.setText("Import model");
        modelsMenu.add(importModelMenuItem);
        modelsMenu.add(jSeparator1);
        thawMenuItem.setText("Thaw all parameters");
        modelsMenu.add(thawMenuItem);
        freezeMenuItem.setText("Freeze all parameters");
        modelsMenu.add(freezeMenuItem);
        jMenuBar1.add(modelsMenu);
        helpMenu.setText("Help");
        helpContentsMenuItem.setText("Help Contents");
        helpMenu.add(helpContentsMenuItem);
        helpOnlineMenuItem.setText("Online user docs");
        helpMenu.add(helpOnlineMenuItem);
        jMenuBar1.add(helpMenu);
        setJMenuBar(jMenuBar1);
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
                getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addGroup(layout
                                .createParallelGroup(
                                        javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addComponent(jPanel2,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addContainerGap())
                .addGroup(layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 435, Short.MAX_VALUE)
                                .addComponent(jInternalFrame1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        0,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 435, Short.MAX_VALUE))));
        layout.setVerticalGroup(layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup().addContainerGap()
                        .addComponent(jPanel1,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(
                                javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE))
                .addGroup(layout
                        .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(0, 326, Short.MAX_VALUE)
                                .addComponent(jInternalFrame1,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        0,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 326, Short.MAX_VALUE))));
        pack();
    }// </editor-fold>//GEN-END:initComponents

    public class TestModel extends AbstractModel {
        public TestModel(String name, String id) {
            super(name, id);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu customModelsMenu;
    private javax.swing.JMenu customModelsMenu1;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu editMenu1;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu fileMenu1;
    private javax.swing.JMenuItem freezeMenuItem;
    private javax.swing.JMenuItem freezeMenuItem1;
    private javax.swing.JMenuItem helpContentsMenuItem;
    private javax.swing.JMenuItem helpContentsMenuItem1;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu helpMenu1;
    private javax.swing.JMenuItem helpOnlineMenuItem;
    private javax.swing.JMenuItem helpOnlineMenuItem1;
    private javax.swing.JMenuItem importModelMenuItem;
    private javax.swing.JMenuItem importModelMenuItem1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTree jTree1;
    private javax.swing.JMenuItem loadModelMenuItem;
    private javax.swing.JMenuItem loadModelMenuItem1;
    private javax.swing.JScrollPane modelComponentsScrollPane;
    private javax.swing.JLabel modelExpressionLabel;
    private javax.swing.JTextField modelExpressionTextField;
    private javax.swing.JPanel modelPropertiesPanel;
    private javax.swing.JMenu modelsMenu;
    private javax.swing.JMenu modelsMenu1;
    private javax.swing.JMenuItem preferencesMenuItem;
    private javax.swing.JMenuItem preferencesMenuItem1;
    private javax.swing.JMenu presetModelsMenu;
    private javax.swing.JMenu presetModelsMenu1;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JMenuItem redoMenuItem1;
    private javax.swing.JMenuItem saveModelMenuItem;
    private javax.swing.JMenuItem saveModelMenuItem1;
    private javax.swing.JMenuItem thawMenuItem;
    private javax.swing.JMenuItem thawMenuItem1;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenuItem undoMenuItem1;
    private javax.swing.JMenuItem writeActiveComponentsMenuItem;
    private javax.swing.JMenuItem writeActiveComponentsMenuItem1;
    private javax.swing.JMenuItem writeAllComponentsMenuItem;
    private javax.swing.JMenuItem writeAllComponentsMenuItem1;
    private javax.swing.JMenu writeToTextMenu;
    private javax.swing.JMenu writeToTextMenu1;
    // End of variables declaration//GEN-END:variables
}