package:
  name: iris
  version: "3.0b2"

build:
  number: 1

requirements:
  run:
   - sherpa-samp 3.0b2

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: A Virtual Observatory tool for Spectral Energy Distributions 
