package:
  name: iris
  version: "3.0"

build:
  number: 1

requirements:
  build:
   - openjdk 8.*
  run:
   - openjdk 8.*
   - sherpa-samp 3.0

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: A Virtual Observatory tool for Spectral Energy Distributions 
