package:
  name: iris
  version: "3.0"

build:
  number: 0

requirements:
  run:
   - sherpa-samp 3.0

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: A Virtual Observatory tool for Spectral Energy Distributions 
