package:
  name: iris
  version: "2.1"

build:
  number: 3 

requirements:
  run:
   - sherpa-samp 2.1

about:
  home: https://github.com/ChandraCXC/sherpa-samp.git
  summary: A Virtual Observatory tool for Spectral Energy Distributions 
