/*
 * Copyright 2016 Chandra X-Ray Observatory.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package cfa.vo.iris.visualizer.plotter;

import cfa.vo.iris.IWorkspace;
import cfa.vo.iris.sed.ExtSed;
import cfa.vo.iris.sed.quantities.SPVYUnit;
import cfa.vo.iris.sed.quantities.XUnit;
import cfa.vo.iris.units.UnitsManager;
import cfa.vo.iris.visualizer.preferences.SedPreferences;
import cfa.vo.iris.visualizer.preferences.VisualizerChangeEvent;
import cfa.vo.iris.visualizer.preferences.VisualizerCommand;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;

/**
 *
 * Unit selection widget. X-units are on the left split pane, Y-units are
 * on the right side.
 */
public class UnitsWidget extends javax.swing.JPanel {

    private ExtSed currentSed;
    private SedPreferences prefs;
    private UnitsManager unitsManager;
    
    /**
     * Creates new form UnitsWidget
     * @param ws - workspace
     * @param prefs - visualizer preferences
     */
    public UnitsWidget(IWorkspace ws, SedPreferences prefs) {
        this.currentSed = (ExtSed) ws.getSedManager().getSelected();
        this.prefs = prefs;
        this.unitsManager = ws.getUnitsManager();
        initComponents();
        
        // if current sed is null, set X and Y to Iris default units
        if (currentSed != null) {
            setXunit(prefs.getXunits());
            setYunit(prefs.getYunits());
        } else {
            // TODO: use default Iris units here; should be a static
            setXunit(unitsManager.newXUnits("Hz").toString());
            setYunit(unitsManager.newYUnits("Jy").toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        xunits = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        yunits = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jSplitPane1.setDividerLocation(200);
        jSplitPane1.setResizeWeight(0.5);

        xunits.setModel(new XUnitsListModel());
        xunits.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${xunit}"), xunits, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(xunits);

        jSplitPane1.setLeftComponent(jScrollPane1);

        yunits.setModel(new YUnitsListModel());
        yunits.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${yunit}"), yunits, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        jScrollPane2.setViewportView(yunits);

        jSplitPane1.setRightComponent(jScrollPane2);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // fire Visualizer event to update plot and MB
        this.prefs.setUnits(xunit, yunit);
        fire(currentSed, VisualizerCommand.RESET);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList xunits;
    private javax.swing.JList yunits;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /*
     * getters and setters
     *
     */
    
    private String xunit;
    public static final String PROP_XUNIT = "xunit";

    /**
     * Get the value of xunit
     *
     * @return the value of xunit
     */
    public String getXunit() {
        return xunit;
    }

    /**
     * Set the value of xunit
     *
     * @param xunit new value of xunit
     */
    public void setXunit(String xunit) {
        String oldXunit = this.xunit;
        this.xunit = xunit;
        //firePropertyChange(PROP_XUNIT, oldXunit, xunit);
    }
    
    private String yunit;
    public static final String PROP_YUNIT = "yunit";

    /**
     * Get the value of yunit
     *
     * @return the value of yunit
     */
    public String getYunit() {
        return yunit;
    }

    /**
     * Set the value of yunit
     *
     * @param yunit new value of yunit
     */
    public void setYunit(String yunit) {
        String oldYunit = this.yunit;
        this.yunit = yunit;
        //firePropertyChange(PROP_YUNIT, oldYunit, yunit);
    }

    
    
    /*
     * end of getters and setters
     *
     */
    
    protected void fire(ExtSed source, VisualizerCommand command) {
        VisualizerChangeEvent.getInstance().fire(source, command);
    }
    
    /*
     * List Models for Y and X units
     *
     */
    
    private class XUnitsListModel extends AbstractListModel {

        List<String> xunits = new ArrayList<>();
        
        public XUnitsListModel() {
            for (XUnit unit : XUnit.values()) {
                xunits.add(unit.getString());
            }
        }
        @Override
        public int getSize() {
            return xunits.size();
        }

        @Override
        public Object getElementAt(int i) {
            return xunits.get(i);
        }
    }
    
    private class YUnitsListModel extends AbstractListModel {

        List<String> yunits = new ArrayList<>();
        
        public YUnitsListModel() {
            for (SPVYUnit unit : SPVYUnit.values()) {
                yunits.add(unit.getString());
            }
        }
        @Override
        public int getSize() {
            return yunits.size();
        }

        @Override
        public Object getElementAt(int i) {
            return yunits.get(i);
        }
    }
}
