#!/bin/bash

function start_iris {

    bindir=$( cd -P "$( dirname "$0" )" && pwd )
    if [ -h "$0" ]; then
        bindir=$( cd -P "$( dirname "`readlink -n "$0"`" )" && pwd )
    fi

    export IRIS_DIR=$bindir

    args="-Xms256m -Xmx1024m -Dhttp.agent=iris/1.1"

    if test -x /usr/bin/sw_vers && /usr/bin/sw_vers | grep -q 'OS.X'; then
      args="$args -Xdock:name=Iris"
    fi

    java $args -DIRIS_DIR=$bindir -jar $bindir/iris-1.1.jar --ssa $@

}

if type -p java; then
    echo Found java executable in PATH
    _java=java
elif [[ -n "$JAVA_HOME" ]] && [[ -x "$JAVA_HOME/bin/java" ]];  then
    echo Found java executable in JAVA_HOME     
    _java="$JAVA_HOME/bin/java"
else
    echo "No java found, quitting. Please follow instructions at http://cxc.cfa.harvard.edu/irisv1.1/download/index.html"
fi

if [[ "$_java" ]]; then
    version=$("$_java" -version 2>&1 | awk -F '"' '/version/ {print $2}')
    echo Found java version "$version"
    if [[ "$version" > "1.6" ]]; then
        echo "This java version is ok, starting Iris"
        start_iris $@
    else         
        echo "This java version is too old, quitting. Please follow instructions at http://cxc.cfa.harvard.edu/irisv1.1/download/index.html"
    fi
fi
