#!/bin/sh

bindir=$( cd -P "$( dirname "$0" )" && pwd )
if [ -h "$0" ]; then
    bindir=$( cd -P "$( dirname "`readlink -n "$0"`" )" && pwd )
fi

export IRIS_DIR=$bindir

args="-Xms256m -Xmx1024m -Dhttp.agent=${project.name}/${project.version}"

if test -x /usr/bin/sw_vers && /usr/bin/sw_vers | grep -q 'OS.X'; then
  args="$args -Xdock:name=Iris"
fi

java $args -DIRIS_DIR=$bindir -jar $bindir/${project.name}-${project.version}.jar --ssa $@



