/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestBuilderFrame.java
 *
 * Created on Dec 16, 2011, 8:02:07 AM
 */
package cfa.vo.iris.test;

import cfa.vo.iris.gui.widgets.SedList;
import cfa.vo.iris.logging.LogEntry;
import cfa.vo.iris.logging.LogEvent;
import cfa.vo.iris.sed.SedlibSedManager;
import cfa.vo.iris.sed.SedlibSedManager.ExtSed;
import cfa.vo.sedlib.Sed;
import cfa.vo.sedlib.Segment;
import cfa.vo.sedlib.io.SedFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author olaurino
 */
public final class TestBuilderFrame extends JInternalFrame {

    private SedlibSedManager manager;

    private SedList sedList;

    /** Creates new form TestBuilderFrame */
    public TestBuilderFrame(final SedlibSedManager manager) {
        super("Test Builder");
        this.manager = manager;
        initComponents();

        sedList = new SedList(manager);

        listPanel.setViewportView(sedList);

        sedList.addListSelectionListener(new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent lse) {
                if(!lse.getValueIsAdjusting()) {
                    JList list = (JList) lse.getSource();
                    setSedSelected(!list.isSelectionEmpty());
                }
            }
        });

    }

    private boolean sedSelected;
    public static final String PROP_SEDSELECTED = "sedSelected";

    /**
     * Get the value of sedSelected
     *
     * @return the value of sedSelected
     */
    public boolean isSedSelected() {
        return sedSelected;
    }

    /**
     * Set the value of sedSelected
     *
     * @param sedSelected new value of sedSelected
     */
    public void setSedSelected(boolean sedSelected) {
        boolean oldSedSelected = this.sedSelected;
        this.sedSelected = sedSelected;
        firePropertyChange(PROP_SEDSELECTED, oldSedSelected, sedSelected);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        newSedButton = new javax.swing.JButton();
        addNedButton = new javax.swing.JButton();
        addUserButton = new javax.swing.JButton();
        removeSegmentButton = new javax.swing.JButton();
        segNumber = new javax.swing.JTextField();
        removeButton = new javax.swing.JButton();
        listPanel = new javax.swing.JScrollPane();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        newSedButton.setText("New SED");
        newSedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSed(evt);
            }
        });

        addNedButton.setText("Add NED Segment to selected SED");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${sedSelected}"), addNedButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        addNedButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNedSegment(evt);
            }
        });

        addUserButton.setText("Add User Segment to selected SED");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${sedSelected}"), addUserButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserSegment(evt);
            }
        });

        removeSegmentButton.setText("Remove Segment: ");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${sedSelected}"), removeSegmentButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        removeSegmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semoveSegment(evt);
            }
        });

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${sedSelected}"), segNumber, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        removeButton.setText("Remove");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${sedSelected}"), removeButton, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        removeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(newSedButton)
                            .add(removeButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(listPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .add(addUserButton)
                    .add(addNedButton)
                    .add(layout.createSequentialGroup()
                        .add(removeSegmentButton)
                        .add(9, 9, 9)
                        .add(segNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(newSedButton)
                        .add(4, 4, 4)
                        .add(removeButton))
                    .add(listPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(addUserButton)
                .add(4, 4, 4)
                .add(addNedButton)
                .add(9, 9, 9)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(1, 1, 1)
                        .add(removeSegmentButton))
                    .add(segNumber, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newSed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSed
        int c = 0;
        while (manager.existsSed("Sed" + c)) {
            c++;
        }

        ExtSed newSed = manager.newSed("Sed" + c);

    }//GEN-LAST:event_newSed

    private void addNedSegment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNedSegment
        try {
            Segment segment = Sed.read(getClass().getResource("/3c066aNED.vot").openStream(), SedFormat.VOT).getSegment(0);
            manager.getSelected().addSegment(segment);
        } catch (Exception ex) {
            Logger.getLogger(TestBuilderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addNedSegment

    private void addUserSegment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserSegment
        try {
            Segment segment = Sed.read(getClass().getResource("/mine.vot").openStream(), SedFormat.VOT).getSegment(0);
            sedList.getSelectedSed().addSegment(segment);
        } catch (Exception ex) {
            Logger.getLogger(TestBuilderFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_addUserSegment

    private void semoveSegment(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semoveSegment
        try {
            Integer i = Integer.parseInt(segNumber.getText());
            sedList.getSelectedSed().removeSegment(i);
        } catch (Exception ex) {
            LogEvent.getInstance().fire(this, new LogEntry("Error parsing segment number:" + segNumber.getText(), this));
        }
    }//GEN-LAST:event_semoveSegment

    private void removeSed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSed
        manager.remove(sedList.getSelectedSed().getId());
    }//GEN-LAST:event_removeSed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNedButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JScrollPane listPanel;
    private javax.swing.JButton newSedButton;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton removeSegmentButton;
    private javax.swing.JTextField segNumber;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


}
