/**
 * Copyright (C) 2012 Smithsonian Astrophysical Observatory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaveSetupDialog.java
 *
 * Created on May 25, 2011, 12:03:17 AM
 */

package cfa.vo.sed.gui;

import cfa.vo.iris.gui.NarrowOptionPane;
import cfa.vo.iris.utils.SpaceTrimmer;
import cfa.vo.sed.builder.SedBuilder;
import cfa.vo.sed.setup.SetupManager;
import cfa.vo.sed.setup.ISetup;
import java.io.File;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;

/**
 *
 * @author olaurino
 */
public class SaveSetupDialog extends javax.swing.JDialog {

    private ISetup conf;

    private boolean isSaveable = false;
    public static final String PROP_ISSAVEABLE = "isSaveable";

    /**
     * Get the value of isSaveable
     *
     * @return the value of isSaveable
     */
    public boolean isIsSaveable() {
        return isSaveable;
    }

    /**
     * Set the value of isSaveable
     *
     * @param isSaveable new value of isSaveable
     */
    public void setIsSaveable(boolean isSaveable) {
        boolean oldIsSaveable = this.isSaveable;
        this.isSaveable = isSaveable;
        firePropertyChange(PROP_ISSAVEABLE, oldIsSaveable, isSaveable);
    }


    private String filePath = "";
    public static final String PROP_FILEPATH = "filePath";

    /**
     * Get the value of filePath
     *
     * @return the value of filePath
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * Set the value of filePath
     *
     * @param filePath new value of filePath
     */
    public void setFilePath(String filePath) {
        filePath = SpaceTrimmer.sideTrim(filePath);
        String oldFilePath = this.filePath;
        this.filePath = filePath;
        firePropertyChange(PROP_FILEPATH, oldFilePath, filePath);
        File f = new File(filePath);
        setIsSaveable(!f.isDirectory());
    }


    /** Creates new form SaveSetupDialog */
    public SaveSetupDialog(java.awt.Frame parent, ISetup conf) {
        super(parent, true);
        initComponents();
        this.setLocationRelativeTo(parent);
        this.conf = conf;
        this.getRootPane().setDefaultButton(jButton2);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Save Setup File");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${filePath}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jButton1.setText("Browse...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1browse(evt);
            }
        });

        jButton2.setText("Save");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${isSaveable}"), jButton2, org.jdesktop.beansbinding.BeanProperty.create("enabled"));
        bindingGroup.addBinding(binding);

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton2)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jButton1)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 301, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1browse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1browse
        JFileChooser jfc = SedBuilder.getWorkspace().getFileChooser();
        jfc.setSelectedFile(new File("setup.ini"));
        File l = new File(filePath);
        if(l.isDirectory())
            jfc.setCurrentDirectory(l);
        jfc.setApproveButtonText("Select");
        int returnval = jfc.showSaveDialog(SedBuilder.getWorkspace().getRootFrame());
        if(returnval == JFileChooser.APPROVE_OPTION) {
            File f = jfc.getSelectedFile();
            String ext = getExtension(f).isEmpty() ? ".ini" : "";
            setFilePath("file://"+f.getAbsolutePath()+ext);
        }
}//GEN-LAST:event_jButton1browse

    private void save(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save
        List<ISetup> confList = new ArrayList();
        confList.add(conf);
        try {
            URL url = new URL(filePath);
            SetupManager.write(confList, url);
            NarrowOptionPane.showMessageDialog(SedBuilder.getWorkspace().getRootFrame(),
                    "Saved file "+filePath, "Saved File", NarrowOptionPane.INFORMATION_MESSAGE);
        } catch (MalformedURLException ex) {
            try {
                File f = new File(filePath);
                URL url = new URL("file://"+f.getAbsolutePath());
                SetupManager.write(confList, url);
                NarrowOptionPane.showMessageDialog(SedBuilder.getWorkspace().getRootFrame(),
                    "Saved file "+filePath, "Saved File", NarrowOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex2) {
                NarrowOptionPane.showMessageDialog(SedBuilder.getWorkspace().getRootFrame(),
                    ex2.getMessage(), "Error saving file", NarrowOptionPane.ERROR_MESSAGE);
            }

        } catch (IOException ex) {
            NarrowOptionPane.showMessageDialog(SedBuilder.getWorkspace().getRootFrame(),
                    ex.getMessage(), "Error saving file", NarrowOptionPane.ERROR_MESSAGE);
        } finally {
            this.dispose();
        }
    }//GEN-LAST:event_save


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jTextField2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /*
     * Get the extension of a file.
     */
    private String getExtension(File f) {
        String ext = "";
        String s = f.getName();
        int i = s.lastIndexOf('.');

        if (i > 0 &&  i < s.length() - 1) {
            ext = s.substring(i+1).toLowerCase();
        }
        
        return ext;
    }


}
