/**
 * Copyright (C) 2012, 2015 Smithsonian Astrophysical Observatory
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VizierFrame.java
 *
 * Created on May 23, 2012, 7:32:18 PM
 */

package cfa.vo.iris.vizier;

import cfa.vo.iris.gui.NarrowOptionPane;
import cfa.vo.iris.sed.ExtSed;
import cfa.vo.iris.sed.ISedManager;
import cfa.vo.iris.sed.SedlibSedManager;
import cfa.vo.sedlib.Segment;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author olaurino
 */
public class VizierFrame extends javax.swing.JInternalFrame {
    private SedlibSedManager manager;

    private String targetName;
    public static final String PROP_TARGETNAME = "targetName";
    
    private String searchRadius = "5";
    public static final String PROP_SEARCHRADIUS = "searchRadius";

    /**
     * Get the value of name
     *
     * @return the value of name
     */
    public String getTargetName() {
        return targetName;
    }
    
    public String getSearchRadius() {
        return searchRadius;
    }

    /**
     * Set the value of name
     *
     * @param name new value of name
     */
    public void setTargetName(String name) {
        String oldName = this.targetName;
        this.targetName = name;
        firePropertyChange(PROP_TARGETNAME, oldName, name);
    }
    
    public void setSearchRadius(String name) {
        String oldName = this.searchRadius;
        this.searchRadius = name;
        firePropertyChange(PROP_SEARCHRADIUS, oldName, name);
    }


    /** Creates new form VizierFrame */
    public VizierFrame(ISedManager manager) {
        initComponents();
        this.manager = (SedlibSedManager) manager;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        sedCreationType = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Vizier Client");
        setMaximumSize(new java.awt.Dimension(200, 100));
        setMinimumSize(new java.awt.Dimension(200, 100));
        setPreferredSize(new java.awt.Dimension(200, 100));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Target Name: ");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        jTextField1.setName("jTextField1"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${targetName}"), jTextField1, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jTextField1);

        getContentPane().add(jPanel1);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel3.setText("Search Radius:");
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel3.add(jLabel3);

        jTextField2.setText("5");
        jTextField2.setName("jTextField2"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${searchRadius}"), jTextField2, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jPanel3.add(jTextField2);

        jLabel2.setText("(arcseconds)");
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel3.add(jLabel2);

        getContentPane().add(jPanel3);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Mode:");
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel2.add(jLabel4);

        sedCreationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Append", "Create" }));
        sedCreationType.setName("sedCreationType"); // NOI18N
        jPanel2.add(sedCreationType);

        jButton1.setText("Load");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                load(evt);
            }
        });
        jPanel2.add(jButton1);

        getContentPane().add(jPanel2);

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void load(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_load
        load();
    }//GEN-LAST:event_load

    private void load() {
        try {
            Collection<Segment> segments = VizierImporter.getSedFromName(targetName, Double.parseDouble(searchRadius));
            ExtSed selectedSed = manager.getSelected();
            
            int idx = sedCreationType.getSelectedIndex();
            boolean add = false;

            if (selectedSed == null || idx == 1) {
                add = true;
                selectedSed = new ExtSed("Vizier", false);
            }
            
            /* Check for duplicate points.
             * 
             * If duplicate point values are in segMap, fire VizierDuplicatePointsFrame
             * and based on the user input, keep or remove all duplicate points.
             * 
             * Check for duplicate points
             * 
             * TODO
             */             

            List<Segment> segs = new ArrayList<>(segments);

            selectedSed.addSegment(segs);
            if (add) {
                manager.add(selectedSed);
            }
        } catch (NumberFormatException ex) {
            Logger.getLogger(VizierFrame.class.getName()).log(Level.SEVERE, null, ex);
            NarrowOptionPane.showMessageDialog(this, "Not a valid search radius: " + searchRadius,
                    "Error", NarrowOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(VizierFrame.class.getName()).log(Level.SEVERE, null, ex);
            NarrowOptionPane.showMessageDialog(this, "Cannot find data for target " + targetName,
                    "Error", NarrowOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JComboBox sedCreationType;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}

